//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarPaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ConsultarPaquete();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarPaquete", ReplyAction="*")]
        System.Threading.Tasks.Task ConsultarPaqueteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarPaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertarPaquete(string destinatario, string remitente, string tipo, int cantidad, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarPaquete", ReplyAction="*")]
        System.Threading.Tasks.Task InsertarPaqueteAsync(string destinatario, string remitente, string tipo, int cantidad, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ModificarPaquete(int id, string destinatario, string remitente, string tipo, int cantidad, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPaquete", ReplyAction="*")]
        System.Threading.Tasks.Task ModificarPaqueteAsync(int id, string destinatario, string remitente, string tipo, int cantidad, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void EliminarPaquete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPaquete", ReplyAction="*")]
        System.Threading.Tasks.Task EliminarPaqueteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarPaquetePorDestinatario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ConsultarPaquetePorDestinatario(string destinatario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarPaquetePorDestinatario", ReplyAction="*")]
        System.Threading.Tasks.Task ConsultarPaquetePorDestinatarioAsync(string destinatario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarPaquetePorRemitente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ConsultarPaquetePorRemitente(string remitente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarPaquetePorRemitente", ReplyAction="*")]
        System.Threading.Tasks.Task ConsultarPaquetePorRemitenteAsync(string remitente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarPaquetePorFecha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ConsultarPaquetePorFecha(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarPaquetePorFecha", ReplyAction="*")]
        System.Threading.Tasks.Task ConsultarPaquetePorFechaAsync(System.DateTime fecha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : MVC.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<MVC.ServiceReference1.WebService1Soap>, MVC.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public void ConsultarPaquete() {
            base.Channel.ConsultarPaquete();
        }
        
        public System.Threading.Tasks.Task ConsultarPaqueteAsync() {
            return base.Channel.ConsultarPaqueteAsync();
        }
        
        public void InsertarPaquete(string destinatario, string remitente, string tipo, int cantidad, string estado) {
            base.Channel.InsertarPaquete(destinatario, remitente, tipo, cantidad, estado);
        }
        
        public System.Threading.Tasks.Task InsertarPaqueteAsync(string destinatario, string remitente, string tipo, int cantidad, string estado) {
            return base.Channel.InsertarPaqueteAsync(destinatario, remitente, tipo, cantidad, estado);
        }
        
        public void ModificarPaquete(int id, string destinatario, string remitente, string tipo, int cantidad, string estado) {
            base.Channel.ModificarPaquete(id, destinatario, remitente, tipo, cantidad, estado);
        }
        
        public System.Threading.Tasks.Task ModificarPaqueteAsync(int id, string destinatario, string remitente, string tipo, int cantidad, string estado) {
            return base.Channel.ModificarPaqueteAsync(id, destinatario, remitente, tipo, cantidad, estado);
        }
        
        public void EliminarPaquete(int id) {
            base.Channel.EliminarPaquete(id);
        }
        
        public System.Threading.Tasks.Task EliminarPaqueteAsync(int id) {
            return base.Channel.EliminarPaqueteAsync(id);
        }
        
        public void ConsultarPaquetePorDestinatario(string destinatario) {
            base.Channel.ConsultarPaquetePorDestinatario(destinatario);
        }
        
        public System.Threading.Tasks.Task ConsultarPaquetePorDestinatarioAsync(string destinatario) {
            return base.Channel.ConsultarPaquetePorDestinatarioAsync(destinatario);
        }
        
        public void ConsultarPaquetePorRemitente(string remitente) {
            base.Channel.ConsultarPaquetePorRemitente(remitente);
        }
        
        public System.Threading.Tasks.Task ConsultarPaquetePorRemitenteAsync(string remitente) {
            return base.Channel.ConsultarPaquetePorRemitenteAsync(remitente);
        }
        
        public void ConsultarPaquetePorFecha(System.DateTime fecha) {
            base.Channel.ConsultarPaquetePorFecha(fecha);
        }
        
        public System.Threading.Tasks.Task ConsultarPaquetePorFechaAsync(System.DateTime fecha) {
            return base.Channel.ConsultarPaquetePorFechaAsync(fecha);
        }
    }
}
